//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASB_ManageAzureServicesGetFees.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5dWIatkp9U3qUncbYQmhbdN1JCAnKAEj8Rvzfpa2WoE=")]
        public string ASB_KeyValue_DEV {
            get {
                return ((string)(this["ASB_KeyValue_DEV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5dWIatkp9U3qUncbYQmhbdN1JCAnKAEj8Rvzfpa2WoE=")]
        public string ASB_KeyValue_UAT {
            get {
                return ((string)(this["ASB_KeyValue_UAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5dWIatkp9U3qUncbYQmhbdN1JCAnKAEj8Rvzfpa2WoE=")]
        public string ASB_KeyValue_STG {
            get {
                return ((string)(this["ASB_KeyValue_STG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5dWIatkp9U3qUncbYQmhbdN1JCAnKAEj8Rvzfpa2WoE=")]
        public string ASB_KeyValue_PRD {
            get {
                return ((string)(this["ASB_KeyValue_PRD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RootManageSharedAccessKey")]
        public string ASB_KeyName_DEV {
            get {
                return ((string)(this["ASB_KeyName_DEV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RootManageSharedAccessKey")]
        public string ASB_KeyName_UAT {
            get {
                return ((string)(this["ASB_KeyName_UAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RootManageSharedAccessKey")]
        public string ASB_KeyName_STG {
            get {
                return ((string)(this["ASB_KeyName_STG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RootManageSharedAccessKey")]
        public string ASB_KeyName_PRD {
            get {
                return ((string)(this["ASB_KeyName_PRD"]));
            }
        }
    }
}
